### ISSUE TITLE
not for windows users

### ISSUE THREAD

**Issue by unkeyn** [ediziks/BingGPT-Discord-Bot#1]
### the instructions need the chmod command, can you extend the instruction for windows users as well?

**Comment by ediziks** [comment]
I don't have a platform to test out windows coverall currently but happy to help out if you'd like to do a PR on it.

**Comment by ediziks** [comment]
The app is now can be run with docker and docker compose as well. To do so;
  - Be sure that docker and docker-compose are installed on your system -> [https://linuxhint.com/install-docker-compose-windows/](https://linuxhint.com/install-docker-compose-windows/)
  - Set the `.env` and `cookies.json` files correctly if not set already
  - Build the project
     `docker-compose build`
  - Run the application
     - `docker-compose up` to run it on your shell, or `docker-compose up -d` to run in detached mode (similar to running as a background process)
