### ISSUE TITLE
Remove login system with Microsoft account 

### ISSUE THREAD

**Issue by DonDoesStuff** [ediziks/BingGPT-Discord-Bot#14]
It is now possible to visit [this page](https://edgeservices.bing.com/edgediscover/query?&darkschemeovr=1&FORM=SHORUN&udscs=1&udsnav=1&setlang=en-US&features=udssydinternal&clientscopes=windowheader,coauthor,chat,&udsframed=1) and not login to use Bing AI, this will also reduce the risk of your Microsoft account getting terminated.

**Comment by ediziks** [comment]
<img width="596" alt="image" src="https://github.com/ediziks/BingGPT-Discord-Bot/assets/54022220/c2491e76-8007-45c5-8607-f8fdba95e3a1">
 I'm facing a join list message with that link actually

**Comment by ediziks** [comment]
Either a cookie or a token is necessary at the moment so will be skipped for a while more.
