### ISSUE TITLE
Bug using Docker

### ISSUE THREAD

**Issue by guguxh** [ediziks/BingGPT-Discord-Bot#15]
I'm using W10 and py 3.10.9, I used docker to build the project but when I try to run I get a error who says dcbot directory doesnt exists, then can't run bot.py.

**Comment by guguxh** [comment]
C:\Users\GUILHERME\Desktop\terraria\gta\Discord\DISCORD I.A\BingGPT-Discord-Bot>docker-compose up
[+] Building 0.1s (0/0)
[+] Running 1/0
 ✔ Container dcbot  Created                                                                                        0.0s
Attaching to dcbot
dcbot  | python3: can't open file './dcbot/bot.py': [Errno 2] No such file or directory
dcbot exited with code 0

**Comment by ediziks** [comment]
Fixed with #16 . Feel free to reopen the ticket if you face with the same bug again.
