### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by guguxh** [ediziks/BingGPT-Discord-Bot#17]
C:\Users\GUILHERME\Desktop\terraria\gta\Discord\DISCORD I.A\BingGPT-Discord-Bot>docker-compose up
[+] Building 0.2s (0/0)
[+] Running 1/1
 ✔ Container dcbot  Recreated                                                                                     14.3s
Attaching to dcbot
dcbot  | Traceback (most recent call last):
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
dcbot  |     yield
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpcore/backends/sync.py", line 100, in connect_tcp
dcbot  |     sock = socket.create_connection(
dcbot  |   File "/usr/local/lib/python3.8/socket.py", line 808, in create_connection
dcbot  |     raise err
dcbot  |   File "/usr/local/lib/python3.8/socket.py", line 796, in create_connection
dcbot  |     sock.connect(sa)
dcbot  | OSError: [Errno 99] Cannot assign requested address
dcbot  |
dcbot  | The above exception was the direct cause of the following exception:
dcbot  |
dcbot  | Traceback (most recent call last):
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
dcbot  |     yield
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 218, in handle_request
dcbot  |     resp = self._pool.handle_request(req)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 261, in handle_request
dcbot  |     raise exc
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
dcbot  |     response = connection.handle_request(request)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 92, in handle_request
dcbot  |     raise exc
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 69, in handle_request
dcbot  |     stream = self._connect(request)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpcore/_sync/connection.py", line 117, in _connect
dcbot  |     stream = self._network_backend.connect_tcp(**kwargs)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpcore/backends/sync.py", line 107, in connect_tcp
dcbot  |     sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
dcbot  |   File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
dcbot  |     self.gen.throw(type, value, traceback)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
dcbot  |     raise to_exc(exc) from exc
dcbot  | httpcore.ConnectError: [Errno 99] Cannot assign requested address
dcbot  |
dcbot  | The above exception was the direct cause of the following exception:
dcbot  |
dcbot  | Traceback (most recent call last):
dcbot  |   File "src/bot.py", line 44, in <module>
dcbot  |     gptbot = Chatbot(cookie_path='cookies.json')
dcbot  |   File "/app/src/EdgeGPT.py", line 604, in __init__
dcbot  |     _Conversation(self.cookies, self.proxy),
dcbot  |   File "/app/src/EdgeGPT.py", line 324, in __init__
dcbot  |     response = self.session.get(
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1041, in get
dcbot  |     return self.request(
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 814, in request
dcbot  |     return self.send(request, auth=auth, follow_redirects=follow_redirects)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 901, in send
dcbot  |     response = self._send_handling_auth(
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 929, in _send_handling_auth
dcbot  |     response = self._send_handling_redirects(
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
dcbot  |     response = self._send_single_request(request)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_client.py", line 1002, in _send_single_request
dcbot  |     response = transport.handle_request(request)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 218, in handle_request
dcbot  |     resp = self._pool.handle_request(req)
dcbot  |   File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
dcbot  |     self.gen.throw(type, value, traceback)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
dcbot  |     raise mapped_exc(message) from exc
dcbot  | httpx.ConnectError: [Errno 99] Cannot assign requested address

**Comment by ediziks** [comment]
Could you elaborate more on the steps followed to produce the error? But first, better to check there's no network or token related issues.

**Comment by ediziks** [comment]
#33
