### ISSUE TITLE
Wheres the problem? how to fix it?

### ISSUE THREAD

**Issue by railomr** [ediziks/BingGPT-Discord-Bot#2]
File "bot.py", line 108, in <module>
    client.run(TOKEN)
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/usr/local/lib/python3.8/dist-packages/discord/client.py", line 621, in login
    await self.setup_hook()
  File "bot.py", line 29, in setup_hook
    await self.tree.sync(guild=MY_GUILD)
  File "/usr/local/lib/python3.8/dist-packages/discord/app_commands/tree.py", line 1069, in sync
    data = await self._http.bulk_upsert_guild_commands(self.client.application_id, guild.id, payload=payload)
  File "/usr/local/lib/python3.8/dist-packages/discord/http.py", line 738, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access

i already checklist the permission too

**Comment by n4free** [comment]
i have same error

**Comment by ediziks** [comment]
I never see that error myself but seems like it might be related to user's account settings. It says that the account holder must have MFA (multi factor authentication) activated on the account they're trying to run the bot. Could you approve that you have MFA activated on your account? Ref: https://stackoverflow.com/a/72149554

**Comment by railomr** [comment]
> I never see that error myself but seems like it might be related to user's account settings. It says that the account holder must have MFA (multi factor authentication) activated on the account they're trying to run the bot. Could you approve that you have MFA activated on your account? Ref: https://stackoverflow.com/a/72149554

sorry but it didnt work

**Comment by railomr** [comment]
> > I never see that error myself but seems like it might be related to user's account settings. It says that the account holder must have MFA (multi factor authentication) activated on the account they're trying to run the bot. Could you approve that you have MFA activated on your account? Ref: https://stackoverflow.com/a/72149554
> 
> sorry but it didnt work

<img width="557" alt="image" src="https://user-images.githubusercontent.com/92773378/227708272-6658d411-babc-4507-a059-dc26d2d3d33e.png">

**Comment by ediziks** [comment]
@railomr I've just pushed a changed on intent permissions reordering. Can you try it again after pulling the repo with recent changes and being sure that your `BOT_TOKEN` and `SERVER_ID` is correct?

**Comment by railomr** [comment]
> @railomr I've just pushed a changed on intent permissions reordering. Can you try it again after pulling the repo with recent changes and being sure that your `BOT_TOKEN` and `SERVER_ID` is correct?

<img width="558" alt="image" src="https://user-images.githubusercontent.com/92773378/227718298-61e8576f-9126-4280-9ed4-2c5979ca81bc.png">
it worked, thank u
