### ISSUE TITLE
error

### ISSUE THREAD

**Issue by pqr29** [ediziks/BingGPT-Discord-Bot#25]
PS C:\Users\usuario\Downloads\BingGPT-Discord-Bot> python src/bot.py
Traceback (most recent call last):
  File "C:\Users\usuario\Downloads\BingGPT-Discord-Bot\src\bot.py", line 44, in <module>
    gptbot = Chatbot(cookie_path='cookies.json')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\usuario\Downloads\BingGPT-Discord-Bot\src\EdgeGPT.py", line 603, in __init__
    self.chat_hub: _ChatHub = _ChatHub(
                              ^^^^^^^^^
  File "C:\Users\usuario\Downloads\BingGPT-Discord-Bot\src\EdgeGPT.py", line 415, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
                           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'conversationSignature'

**Comment by de-joit** [comment]
Same problem

**Comment by xrmaalk** [comment]
same. any idea where we can find the conversationSignature key?

**Comment by xrmaalk** [comment]
Hi guys, I was able to get the code working by adjusting line 415 EdgeGPT.py . 

I added the .get method to the .struct which solved the error. here is the adjusted code snippet:


self.request = _ChatHubRequest(
            conversation_signature=conversation.struct.get("conversationSignature"),
            client_id=conversation.struct["clientId"],
            conversation_id=conversation.struct["conversationId"],
        )

**Comment by xrmaalk** [comment]
Has anyone got the bot functioning/responding on their discord server?
