### ISSUE TITLE
error -docker

### ISSUE THREAD

**Issue by astrotically** [ediziks/BingGPT-Discord-Bot#32]
dcbot  | Traceback (most recent call last):
dcbot  |   File "src/bot.py", line 175, in <module>
dcbot  |     client.run(TOKEN)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 860, in run
dcbot  |     asyncio.run(runner())
dcbot  |   File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
dcbot  |     return loop.run_until_complete(main)
dcbot  |   File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
dcbot  |     return future.result()
dcbot  |   File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 849, in runner
dcbot  |     await self.start(token, reconnect=reconnect)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 777, in start
dcbot  |     await self.login(token)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/discord/client.py", line 621, in login
dcbot  |     await self.setup_hook()
dcbot  |   File "src/bot.py", line 30, in setup_hook
dcbot  |     await self.tree.sync(guild=MY_GUILD)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/discord/app_commands/tree.py", line 1069, in sync
dcbot  |     data = await self._http.bulk_upsert_guild_commands(self.client.application_id, guild.id, payload=payload)
dcbot  |   File "/usr/local/lib/python3.8/site-packages/discord/http.py", line 739, in request
dcbot  |     raise Forbidden(response, data)
dcbot  | discord.errors.Forbidden: 403 Forbidden (error code: 50001): Missing Access
dcbot exited with code 0

help asap! i did everything right

**Comment by ediziks** [comment]
#33
