### ISSUE TITLE
error using /imagine

### ISSUE THREAD

**Issue by reonjy112** [ediziks/BingGPT-Discord-Bot#7]
Error: [Errno 5] I/O error
Try again or check if your prompt is appropriate.

any fix for this?

**Comment by ediziks** [comment]
Do you only have this error whenever you try or occasionally?

**Comment by reonjy112** [comment]
> Do you only have this error whenever you try or occasionally? And, which command triggers the error?

everytime i try, the /ask command works though, just the /imagine

**Comment by reonjy112** [comment]
when i use /imagine then type my prompt, it gives me that result.. the /ask works just fine.

**Comment by ediziks** [comment]
Most probably it's related to expired cookies. Please try updating your cookies again and better if you do it on the most recent version.
